version: 0.2

env:
  variables:
    BLOG_CONF_DIR: "my-blog-config"
    BLOG_CONF_REPO: "aweimeow/my-blog-config.git"

phases:
  install:
    commands:
      - echo Entered the install phase...
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - git clone https://aweimeow:$GITHUB_OAUTH_KEY@github.com/$BLOG_CONF_REPO
      - npm install
      - npm install hexo-cli -g
  build:
    commands:
      - echo "Build started on `date`, triggered by $CODEBUILD_WEBHOOK_TRIGGER"
      - cp $BLOG_CONF_DIR/conf/* .
      - cp $BLOG_CONF_DIR/js/* ./node_modules/hexo-theme-icarus/scripts/
      - cp $BLOG_CONF_DIR/img/* ./node_modules/hexo-theme-icarus/source/img/
      - cp $BLOG_CONF_DIR/css/custom.styl ./node_modules/hexo-theme-icarus/source/css/
      - echo "@import 'custom'" >> ./node_modules/hexo-theme-icarus/source/css/default.styl
      - ls -al ./node_modules/hexo-theme-icarus/source/css
      - hexo generate
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: public
  secondary-artifacts:
    artifact1:
      files:
        - '**/*'
      base-directory: public
      discard-paths: no
